name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache Runtimes
      uses: actions/cache@v2
      with:
        path: .runtimes
        key: standard-key

    - name: Cache Zephyr
      uses: actions/cache@v2
      with:
        path: target
        key: standard-key

    - name: Runtime Installs
      shell: bash
      run: |
          [[ -d .runtimes ]] || mkdir .runtimes
          if [[ ! -f .runtimes/wasmtime ]]; then
            curl https://wasmtime.dev/install.sh -sSf | bash
            mv $HOME/.wasmtime/bin/wasmtime .runtimes/wasmtime
          fi

    - name: Build
      run:
        cargo build --verbose

    - name: Run rust tests
      run: cargo test --verbose

    - name: Run Zephyr test-suite
      shell: bash
      run: |
          export PATH=".runtimes:$PATH"
          export ZEPHYR_LIB=`pwd`/lib
          python tests.py --debug
